### ISSUE TITLE
My Files , Downloaded and Published page logic is not correct

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry-web-ui#110]
For the "My File" page, content is seperated into "Downloaded" and "Published" page by checking if user has made a name claim associated with that file. This does not take into consideration that you can download a file with the same name claim (since there can be multiple claims on name). 

It should check the lbry_sd_hash of the file with the name claim's attached lbry_sd_hash to make sure that user owns the file.

**Comment by kaykurokawa** [comment]
This unmerged pull request will fix this issue https://github.com/lbryio/lbry-web-ui/pull/77

**Comment by alexliebowitz** [comment]
#77 was merged, so this is resolved.
