### ISSUE TITLE
My files page fails to load if non standard claims are used 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry-web-ui#119]
My files page assumes that all claims returned with getMyClaims will return a standard JSON serializeable metadata with a lbry sd hash.  Claims may not contain JSON serializable metadata, and it may not contain a lbry sd hash. If a user has such claims, the My files page will fail to load. The proper behavior should probably just ignore these non standard claims.

https://github.com/lbryio/lbry-web-ui/blob/5d3110a295ee4cfb055f92ac7db0b2a7206bd59c/js/page/my_files.js#L223

**Comment by kauffj** [comment]
I believe it was decided that it's the daemon's job to return well-formed data (i.e. the daemon API is promising a certain structure), and that it is not the web UI's job to ensure the data is well structured. Re-open this if I am mistaken or you think this is wrong.
