### ISSUE TITLE
On my files, metadata.content_type can be undefined

### ISSUE THREAD

**Issue by jobevers** [lbryio/lbry-web-ui#136]
![image](https://cloud.githubusercontent.com/assets/2380127/22050213/79f9ff32-dcfe-11e6-8176-2b7aff8fc5e8.png)

Which causes

![image](https://cloud.githubusercontent.com/assets/2380127/22050227/9898c0b8-dcfe-11e6-8e76-31b06e453919.png)

**Comment by alexliebowitz** [comment]
Fixed by Job in #135.
