### ISSUE TITLE
The text for items in front page overflows past the box 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry-web-ui#163]
On Ubuntu 16.04, firefox 51.0.1, the text for items on the front page overflows past the box

![textoverflow](https://cloud.githubusercontent.com/assets/7075051/22796223/97abcad0-eec7-11e6-9b1a-a5a1278484f9.png)

**Comment by alexliebowitz** [comment]
This was fixed in #165 but I think it never landed in master--but it's moot now with Electron
