### ISSUE TITLE
Stop showing the 1000LBC popup on every page

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-web-ui#3]
I understand that we don't want people doing stuff until the faucet comes through, but there's gotta be a better design for that than a nagging popup

**Comment by alexliebowitz** [comment]
Fixed it so it only appears on the home page. It will still appear if you return to the home page during the same daemon run. That can be fixed if we switch to history object based routing; Jeremy suggested we think about that and it seems like a good idea.
