### ISSUE TITLE
Inteface changes for txid + nout 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry-web-ui#78]
Below is the changed command for lbrynet for the txid + nout patch https://github.com/lbryio/lbry/pull/245 which should be relevant for lbry web ui

publish() 
https://github.com/kaykurokawa/lbry/blob/7a669c188d67d6b7474b88952440afdc72c8bf28/lbrynet/lbrynet_daemon/Daemon.py#L1671
 - before, this returned the txid of the claim after finishing publishing
 - now, this returns a dictionary with the below contents
            'success' : True if claim was succesful , False otherwise                            
            'reason' : if not succesful, give reason
            'txid' : txid of resulting transaction if succesful
            'nout' : nout of the resulting support claim if succesful
            'fee' : fee paid for the claim transaction if succesful
            'claimid' : claimid of the resulting transaction

The input to publish is still the same , and I think if you were not using the output in the original interface for anything you should be ok. 

I think you are not using abandon_claim, and support_claim which also changed, but below is the change for those two commands if you are interested. 

abandon_claim() 
https://github.com/kaykurokawa/lbry/blob/7a669c188d67d6b7474b88952440afdc72c8bf28/lbrynet/lbrynet_daemon/Daemon.py#L1757
- before this took as input the txid of the claim to abandon
- now this takes as input txid and nout

- before this returned the txid of the resulting abandon transaction if succesful 
- now this returns a dictionary with the below contents
 
            success : True if succesful , False otherwise
            reason : if not succesful, give reason
            txid : txid of resulting transaction if succesful
            fee : fee paid for the transaction if succesful 

support_claim()
https://github.com/kaykurokawa/lbry/blob/7a669c188d67d6b7474b88952440afdc72c8bf28/lbrynet/lbrynet_daemon/Daemon.py#L1800
- before this returned the txid of the resulting support if succesful 
- now this returns a dictionary with the below contents

            success : True if succesful , False otherwise
            reason : if not succesful, give reason
            txid : txid of resulting transaction if succesful
            nout : nout of the resulting support claim if succesful
            fee : fee paid for the transaction if succesful

**Comment by alexliebowitz** [comment]
The API currently doesn't use support_claim/abandon_claim or the output from publish, so this didn't require any action.
