### ISSUE TITLE
Upload Breaks if Publish is Clicked before File is Processed

### ISSUE THREAD

**Issue by benyanke** [lbryio/lbry-web-ui#85]
If a file is uploaded, and "publish" is clicked before it's finished processing, it will get stuck forever in the processing phase and never complete. 

Suggestion: grey out the "publish" button until the file is processed, or add another error checker, like there is with the blank-field-check in the form entries.

**Comment by alexliebowitz** [comment]
Thanks, Ben. PR #92 fixes this.
